## Some lines I'm not using anymore for analysing learning experiments

# Following line turns "true" column entry into numeric vector
#as.numeric(unlist(strsplit(as.character(learningData$true[1]), split = " ")))[1]

#mse = function(x, y) { sum((x - y)^2) / length(x) }

#true1 = as.numeric(unlist(strsplit(as.character(learningData$true[1]), split = " ")))
#learnt1 = as.numeric(unlist(strsplit(as.character(learningData$learnt[1]), split = " ")))

groupsChain = rep(2:15, each = 100)

# meansNormalChainSamples100GradDescent = c(mean(mseNormalChain2samples100gradDescent),
#                                           mean(mseNormalChain3samples100gradDescent),
#                                           mean(mseNormalChain4samples100gradDescent),
#                                           mean(mseNormalChain5samples100gradDescent),
#                                           mean(mseNormalChain6samples100gradDescent),
#                                           mean(mseNormalChain7samples100gradDescent),
#                                           mean(mseNormalChain8samples100gradDescent),
#                                           mean(mseNormalChain9samples100gradDescent),
#                                           mean(mseNormalChain10samples100gradDescent),
#                                           mean(mseNormalChain11samples100gradDescent),
#                                           mean(mseNormalChain12samples100gradDescent),
#                                           mean(mseNormalChain13samples100gradDescent),
#                                           mean(mseNormalChain14samples100gradDescent),
#                                           mean(mseNormalChain15samples100gradDescent))

# qlNormalChainSamples100GradDescent = c(quantile(mseNormalChain2samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain3samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain4samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain5samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain6samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain7samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain8samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain9samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain10samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain11samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain12samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain13samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain14samples100gradDescent, probs = c(0.25)),
#                                        quantile(mseNormalChain15samples100gradDescent, probs = c(0.25)))

#plot(2:15, meansNormalChainSamples100GradDescent)
#points(2:15, qlNormalChainSamples100GradDescent

#boxplot(msesNormalChainSamples100GradDescent ~ groupsChain, outline = FALSE, main = "Normal Chain 100 GradDescent")

#x = 2:15
#lines(predict(loess(meansNormalChainSamples100GradDescent ~ x)), xlim = c(2, 15))
#scatter.smooth(2:15, meansNormalChainSamples100GradDescent, span = 1)

msesNormalChainSamples1000GradDescent = c((mseNormalChain2samples1000gradDescent),
                                          (mseNormalChain3samples1000gradDescent),
                                          (mseNormalChain4samples1000gradDescent),
                                          (mseNormalChain5samples1000gradDescent),
                                          (mseNormalChain6samples1000gradDescent),
                                          (mseNormalChain7samples1000gradDescent),
                                          (mseNormalChain8samples1000gradDescent),
                                          (mseNormalChain9samples1000gradDescent),
                                          (mseNormalChain10samples1000gradDescent),
                                          (mseNormalChain11samples1000gradDescent),
                                          (mseNormalChain12samples1000gradDescent),
                                          (mseNormalChain13samples1000gradDescent),
                                          (mseNormalChain14samples1000gradDescent),
                                          (mseNormalChain15samples1000gradDescent))

groupsChain = c(rep(2, length(mseNormalChain2samples1000gradDescent)),
                rep(3, length(mseNormalChain3samples1000gradDescent)),
                rep(4, length(mseNormalChain4samples1000gradDescent)),
                rep(5, length(mseNormalChain5samples1000gradDescent)),
                rep(6, length(mseNormalChain6samples1000gradDescent)),
                rep(7, length(mseNormalChain7samples1000gradDescent)),
                rep(8, length(mseNormalChain8samples1000gradDescent)),
                rep(9, length(mseNormalChain9samples1000gradDescent)),
                rep(10, length(mseNormalChain10samples1000gradDescent)),
                rep(11, length(mseNormalChain11samples1000gradDescent)),
                rep(12, length(mseNormalChain12samples1000gradDescent)),
                rep(13, length(mseNormalChain13samples1000gradDescent)),
                rep(14, length(mseNormalChain14samples1000gradDescent)),
                rep(15, length(mseNormalChain15samples1000gradDescent)))

#boxplot(msesNormalChainSamples1000GradDescent ~ groupsChain, outline = FALSE, main = "Normal Chain 1000 GradDescent")

bootMedian <- function(d, i){
  d2 <- d[i]
  return(median(d2) + rnorm(1, 0, 1 / sqrt(length(d))))
}

bootMean <- function(d, i){
  d2 <- d[i]
  return(mean(d2))
}

sdMediansNormalLoopSamples100GradDescent = c(sd(boot(mseNormalLoop3samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop4samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop5samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop6samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop7samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop8samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop9samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop10samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop11samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop12samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop13samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop14samples100gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(mseNormalLoop15samples100gradDescent, bootMedian, R = 500)$t))

sdMediansNormalLoopSamples1000GradDescent = c(sd(boot(mseNormalLoop3samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop4samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop5samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop6samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop7samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop8samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop9samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop10samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop11samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop12samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop13samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop14samples1000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseNormalLoop15samples1000gradDescent, bootMedian, R = 500)$t))

sdMediansNormalLoopSamples10000GradDescent = c(sd(boot(mseNormalLoop3samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop4samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop5samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop6samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop7samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop8samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop9samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop10samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop11samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop12samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop13samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop14samples10000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseNormalLoop15samples10000gradDescent, bootMedian, R = 500)$t))

sdMediansClaytonLoopSamples100GradDescent = c(sd(boot(mseClaytonLoop3samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop4samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop5samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop6samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop7samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop8samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop9samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop10samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop11samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop12samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop13samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop14samples100gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(mseClaytonLoop15samples100gradDescent, bootMedian, R = 500)$t))

sdMediansClaytonLoopSamples1000GradDescent = c(sd(boot(mseClaytonLoop3samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop4samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop5samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop6samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop7samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop8samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop9samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop10samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop11samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop12samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop13samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop14samples1000gradDescent, bootMedian, R = 500)$t),
                                               sd(boot(mseClaytonLoop15samples1000gradDescent, bootMedian, R = 500)$t))

sdMediansClaytonLoopSamples10000GradDescent = c(sd(boot(mseClaytonLoop3samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop4samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop5samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop6samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop7samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop8samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop9samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop10samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop11samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop12samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop13samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop14samples10000gradDescent, bootMedian, R = 500)$t),
                                                sd(boot(mseClaytonLoop15samples10000gradDescent, bootMedian, R = 500)$t))

sdMediansNormalLoopSamples100Restart = c(sd(boot(mseNormalLoop3samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop4samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop5samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop6samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop7samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop8samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop9samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop10samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop11samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop12samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop13samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop14samples100restart, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop15samples100restart, bootMedian, R = 500)$t))

sdMediansNormalLoopSamples1000Restart = c(sd(boot(mseNormalLoop3samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop4samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop5samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop6samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop7samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop8samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop9samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop10samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop11samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop12samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop13samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop14samples1000restart, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop15samples1000restart, bootMedian, R = 500)$t))

sdMediansNormalLoopSamples10000Restart = c(sd(boot(mseNormalLoop3samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop4samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop5samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop6samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop7samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop8samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop9samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop10samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop11samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop12samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop13samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop14samples10000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop15samples10000restart, bootMedian, R = 500)$t))

sdMediansClaytonLoopSamples100Restart = c(sd(boot(mseClaytonLoop3samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop4samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop5samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop6samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop7samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop8samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop9samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop10samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop11samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop12samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop13samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop14samples100restart, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop15samples100restart, bootMedian, R = 500)$t))

sdMediansClaytonLoopSamples1000Restart = c(sd(boot(mseClaytonLoop3samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop4samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop5samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop6samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop7samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop8samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop9samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop10samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop11samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop12samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop13samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop14samples1000restart, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop15samples1000restart, bootMedian, R = 500)$t))

sdMediansClaytonLoopSamples10000Restart = c(sd(boot(mseClaytonLoop3samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop4samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop5samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop6samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop7samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop8samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop9samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop10samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop11samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop12samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop13samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop14samples10000restart, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop15samples10000restart, bootMedian, R = 500)$t))

sdMediansNormalLoopSamples100Barrier = c(sd(boot(mseNormalLoop3samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop4samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop5samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop6samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop7samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop8samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop9samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop10samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop11samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop12samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop13samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop14samples100barrier, bootMedian, R = 500)$t),
                                         sd(boot(mseNormalLoop15samples100barrier, bootMedian, R = 500)$t))

sdMediansNormalLoopSamples1000Barrier = c(sd(boot(mseNormalLoop3samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop4samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop5samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop6samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop7samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop8samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop9samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop10samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop11samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop12samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop13samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop14samples1000barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseNormalLoop15samples1000barrier, bootMedian, R = 500)$t))

sdMediansNormalLoopSamples10000Barrier = c(sd(boot(mseNormalLoop3samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop4samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop5samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop6samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop7samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop8samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop9samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop10samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop11samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop12samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop13samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop14samples10000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseNormalLoop15samples10000barrier, bootMedian, R = 500)$t))

sdMediansClaytonLoopSamples100Barrier = c(sd(boot(mseClaytonLoop3samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop4samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop5samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop6samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop7samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop8samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop9samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop10samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop11samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop12samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop13samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop14samples100barrier, bootMedian, R = 500)$t),
                                          sd(boot(mseClaytonLoop15samples100barrier, bootMedian, R = 500)$t))

sdMediansClaytonLoopSamples1000Barrier = c(sd(boot(mseClaytonLoop3samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop4samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop5samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop6samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop7samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop8samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop9samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop10samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop11samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop12samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop13samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop14samples1000barrier, bootMedian, R = 500)$t),
                                           sd(boot(mseClaytonLoop15samples1000barrier, bootMedian, R = 500)$t))

sdMediansClaytonLoopSamples10000Barrier = c(sd(boot(mseClaytonLoop3samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop4samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop5samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop6samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop7samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop8samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop9samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop10samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop11samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop12samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop13samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop14samples10000barrier, bootMedian, R = 500)$t),
                                            sd(boot(mseClaytonLoop15samples10000barrier, bootMedian, R = 500)$t))

sdItersNormalLoopSamples100GradDescent = c(sd(boot(itersNormalLoop3samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop4samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop5samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop6samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop7samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop8samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop9samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop10samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop11samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop12samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop13samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop14samples100gradDescent, bootMedian, R = 500)$t),
                                           sd(boot(itersNormalLoop15samples100gradDescent, bootMedian, R = 500)$t))

sdItersNormalLoopSamples1000GradDescent = c(sd(boot(itersNormalLoop3samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop4samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop5samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop6samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop7samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop8samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop9samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop10samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop11samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop12samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop13samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop14samples1000gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersNormalLoop15samples1000gradDescent, bootMedian, R = 500)$t))

sdItersNormalLoopSamples10000GradDescent = c(sd(boot(itersNormalLoop3samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop4samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop5samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop6samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop7samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop8samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop9samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop10samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop11samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop12samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop13samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop14samples10000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersNormalLoop15samples10000gradDescent, bootMedian, R = 500)$t))

sdItersClaytonLoopSamples100GradDescent = c(sd(boot(itersClaytonLoop3samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop4samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop5samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop6samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop7samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop8samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop9samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop10samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop11samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop12samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop13samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop14samples100gradDescent, bootMedian, R = 500)$t),
                                            sd(boot(itersClaytonLoop15samples100gradDescent, bootMedian, R = 500)$t))

sdItersClaytonLoopSamples1000GradDescent = c(sd(boot(itersClaytonLoop3samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop4samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop5samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop6samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop7samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop8samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop9samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop10samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop11samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop12samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop13samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop14samples1000gradDescent, bootMedian, R = 500)$t),
                                             sd(boot(itersClaytonLoop15samples1000gradDescent, bootMedian, R = 500)$t))

sdItersClaytonLoopSamples10000GradDescent = c(sd(boot(itersClaytonLoop3samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop4samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop5samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop6samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop7samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop8samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop9samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop10samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop11samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop12samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop13samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop14samples10000gradDescent, bootMedian, R = 500)$t),
                                              sd(boot(itersClaytonLoop15samples10000gradDescent, bootMedian, R = 500)$t))

sdItersNormalLoopSamples100Restart = c(sd(boot(itersNormalLoop3samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop4samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop5samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop6samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop7samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop8samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop9samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop10samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop11samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop12samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop13samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop14samples100restart, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop15samples100restart, bootMedian, R = 500)$t))

sdItersNormalLoopSamples1000Restart = c(sd(boot(itersNormalLoop3samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop4samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop5samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop6samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop7samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop8samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop9samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop10samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop11samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop12samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop13samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop14samples1000restart, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop15samples1000restart, bootMedian, R = 500)$t))

sdItersNormalLoopSamples10000Restart = c(sd(boot(itersNormalLoop3samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop4samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop5samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop6samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop7samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop8samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop9samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop10samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop11samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop12samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop13samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop14samples10000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop15samples10000restart, bootMedian, R = 500)$t))

sdItersClaytonLoopSamples100Restart = c(sd(boot(itersClaytonLoop3samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop4samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop5samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop6samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop7samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop8samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop9samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop10samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop11samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop12samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop13samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop14samples100restart, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop15samples100restart, bootMedian, R = 500)$t))

sdItersClaytonLoopSamples1000Restart = c(sd(boot(itersClaytonLoop3samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop4samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop5samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop6samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop7samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop8samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop9samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop10samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop11samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop12samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop13samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop14samples1000restart, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop15samples1000restart, bootMedian, R = 500)$t))

sdItersClaytonLoopSamples10000Restart = c(sd(boot(itersClaytonLoop3samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop4samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop5samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop6samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop7samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop8samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop9samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop10samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop11samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop12samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop13samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop14samples10000restart, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop15samples10000restart, bootMedian, R = 500)$t))

sdItersNormalLoopSamples100Barrier = c(sd(boot(itersNormalLoop3samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop4samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop5samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop6samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop7samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop8samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop9samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop10samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop11samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop12samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop13samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop14samples100barrier, bootMedian, R = 500)$t),
                                       sd(boot(itersNormalLoop15samples100barrier, bootMedian, R = 500)$t))

sdItersNormalLoopSamples1000Barrier = c(sd(boot(itersNormalLoop3samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop4samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop5samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop6samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop7samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop8samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop9samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop10samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop11samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop12samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop13samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop14samples1000barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersNormalLoop15samples1000barrier, bootMedian, R = 500)$t))

sdItersNormalLoopSamples10000Barrier = c(sd(boot(itersNormalLoop3samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop4samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop5samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop6samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop7samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop8samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop9samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop10samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop11samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop12samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop13samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop14samples10000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersNormalLoop15samples10000barrier, bootMedian, R = 500)$t))

sdItersClaytonLoopSamples100Barrier = c(sd(boot(itersClaytonLoop3samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop4samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop5samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop6samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop7samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop8samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop9samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop10samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop11samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop12samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop13samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop14samples100barrier, bootMedian, R = 500)$t),
                                        sd(boot(itersClaytonLoop15samples100barrier, bootMedian, R = 500)$t))

sdItersClaytonLoopSamples1000Barrier = c(sd(boot(itersClaytonLoop3samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop4samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop5samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop6samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop7samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop8samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop9samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop10samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop11samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop12samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop13samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop14samples1000barrier, bootMedian, R = 500)$t),
                                         sd(boot(itersClaytonLoop15samples1000barrier, bootMedian, R = 500)$t))

sdItersClaytonLoopSamples10000Barrier = c(sd(boot(itersClaytonLoop3samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop4samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop5samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop6samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop7samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop8samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop9samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop10samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop11samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop12samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop13samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop14samples10000barrier, bootMedian, R = 500)$t),
                                          sd(boot(itersClaytonLoop15samples10000barrier, bootMedian, R = 500)$t))

numNormalLoopSamples100GradDescent = c(length(mseNormalLoop3samples100gradDescent),
                                       length(mseNormalLoop4samples100gradDescent),
                                       length(mseNormalLoop5samples100gradDescent),
                                       length(mseNormalLoop6samples100gradDescent),
                                       length(mseNormalLoop7samples100gradDescent),
                                       length(mseNormalLoop8samples100gradDescent),
                                       length(mseNormalLoop9samples100gradDescent),
                                       length(mseNormalLoop10samples100gradDescent),
                                       length(mseNormalLoop11samples100gradDescent),
                                       length(mseNormalLoop12samples100gradDescent),
                                       length(mseNormalLoop13samples100gradDescent),
                                       length(mseNormalLoop14samples100gradDescent),
                                       length(mseNormalLoop15samples100gradDescent))

numNormalLoopSamples1000GradDescent = c(length(mseNormalLoop3samples1000gradDescent),
                                        length(mseNormalLoop4samples1000gradDescent),
                                        length(mseNormalLoop5samples1000gradDescent),
                                        length(mseNormalLoop6samples1000gradDescent),
                                        length(mseNormalLoop7samples1000gradDescent),
                                        length(mseNormalLoop8samples1000gradDescent),
                                        length(mseNormalLoop9samples1000gradDescent),
                                        length(mseNormalLoop10samples1000gradDescent),
                                        length(mseNormalLoop11samples1000gradDescent),
                                        length(mseNormalLoop12samples1000gradDescent),
                                        length(mseNormalLoop13samples1000gradDescent),
                                        length(mseNormalLoop14samples1000gradDescent),
                                        length(mseNormalLoop15samples1000gradDescent))

numNormalLoopSamples10000GradDescent = c(length(mseNormalLoop3samples10000gradDescent),
                                         length(mseNormalLoop4samples10000gradDescent),
                                         length(mseNormalLoop5samples10000gradDescent),
                                         length(mseNormalLoop6samples10000gradDescent),
                                         length(mseNormalLoop7samples10000gradDescent),
                                         length(mseNormalLoop8samples10000gradDescent),
                                         length(mseNormalLoop9samples10000gradDescent),
                                         length(mseNormalLoop10samples10000gradDescent),
                                         length(mseNormalLoop11samples10000gradDescent),
                                         length(mseNormalLoop12samples10000gradDescent),
                                         length(mseNormalLoop13samples10000gradDescent),
                                         length(mseNormalLoop14samples10000gradDescent),
                                         length(mseNormalLoop15samples10000gradDescent))

numClaytonLoopSamples100GradDescent = c(length(mseClaytonLoop3samples100gradDescent),
                                        length(mseClaytonLoop4samples100gradDescent),
                                        length(mseClaytonLoop5samples100gradDescent),
                                        length(mseClaytonLoop6samples100gradDescent),
                                        length(mseClaytonLoop7samples100gradDescent),
                                        length(mseClaytonLoop8samples100gradDescent),
                                        length(mseClaytonLoop9samples100gradDescent),
                                        length(mseClaytonLoop10samples100gradDescent),
                                        length(mseClaytonLoop11samples100gradDescent),
                                        length(mseClaytonLoop12samples100gradDescent),
                                        length(mseClaytonLoop13samples100gradDescent),
                                        length(mseClaytonLoop14samples100gradDescent),
                                        length(mseClaytonLoop15samples100gradDescent))

numClaytonLoopSamples1000GradDescent = c(length(mseClaytonLoop3samples1000gradDescent),
                                         length(mseClaytonLoop4samples1000gradDescent),
                                         length(mseClaytonLoop5samples1000gradDescent),
                                         length(mseClaytonLoop6samples1000gradDescent),
                                         length(mseClaytonLoop7samples1000gradDescent),
                                         length(mseClaytonLoop8samples1000gradDescent),
                                         length(mseClaytonLoop9samples1000gradDescent),
                                         length(mseClaytonLoop10samples1000gradDescent),
                                         length(mseClaytonLoop11samples1000gradDescent),
                                         length(mseClaytonLoop12samples1000gradDescent),
                                         length(mseClaytonLoop13samples1000gradDescent),
                                         length(mseClaytonLoop14samples1000gradDescent),
                                         length(mseClaytonLoop15samples1000gradDescent))

numClaytonLoopSamples10000GradDescent = c(length(mseClaytonLoop3samples10000gradDescent),
                                          length(mseClaytonLoop4samples10000gradDescent),
                                          length(mseClaytonLoop5samples10000gradDescent),
                                          length(mseClaytonLoop6samples10000gradDescent),
                                          length(mseClaytonLoop7samples10000gradDescent),
                                          length(mseClaytonLoop8samples10000gradDescent),
                                          length(mseClaytonLoop9samples10000gradDescent),
                                          length(mseClaytonLoop10samples10000gradDescent),
                                          length(mseClaytonLoop11samples10000gradDescent),
                                          length(mseClaytonLoop12samples10000gradDescent),
                                          length(mseClaytonLoop13samples10000gradDescent),
                                          length(mseClaytonLoop14samples10000gradDescent),
                                          length(mseClaytonLoop15samples10000gradDescent))

numNormalLoopSamples100Restart = c(length(mseNormalLoop3samples100restart),
                                   length(mseNormalLoop4samples100restart),
                                   length(mseNormalLoop5samples100restart),
                                   length(mseNormalLoop6samples100restart),
                                   length(mseNormalLoop7samples100restart),
                                   length(mseNormalLoop8samples100restart),
                                   length(mseNormalLoop9samples100restart),
                                   length(mseNormalLoop10samples100restart),
                                   length(mseNormalLoop11samples100restart),
                                   length(mseNormalLoop12samples100restart),
                                   length(mseNormalLoop13samples100restart),
                                   length(mseNormalLoop14samples100restart),
                                   length(mseNormalLoop15samples100restart))

numNormalLoopSamples1000Restart = c(length(mseNormalLoop3samples1000restart),
                                    length(mseNormalLoop4samples1000restart),
                                    length(mseNormalLoop5samples1000restart),
                                    length(mseNormalLoop6samples1000restart),
                                    length(mseNormalLoop7samples1000restart),
                                    length(mseNormalLoop8samples1000restart),
                                    length(mseNormalLoop9samples1000restart),
                                    length(mseNormalLoop10samples1000restart),
                                    length(mseNormalLoop11samples1000restart),
                                    length(mseNormalLoop12samples1000restart),
                                    length(mseNormalLoop13samples1000restart),
                                    length(mseNormalLoop14samples1000restart),
                                    length(mseNormalLoop15samples1000restart))

numNormalLoopSamples10000Restart = c(length(mseNormalLoop3samples10000restart),
                                     length(mseNormalLoop4samples10000restart),
                                     length(mseNormalLoop5samples10000restart),
                                     length(mseNormalLoop6samples10000restart),
                                     length(mseNormalLoop7samples10000restart),
                                     length(mseNormalLoop8samples10000restart),
                                     length(mseNormalLoop9samples10000restart),
                                     length(mseNormalLoop10samples10000restart),
                                     length(mseNormalLoop11samples10000restart),
                                     length(mseNormalLoop12samples10000restart),
                                     length(mseNormalLoop13samples10000restart),
                                     length(mseNormalLoop14samples10000restart),
                                     length(mseNormalLoop15samples10000restart))

numClaytonLoopSamples100Restart = c(length(mseClaytonLoop3samples100restart),
                                    length(mseClaytonLoop4samples100restart),
                                    length(mseClaytonLoop5samples100restart),
                                    length(mseClaytonLoop6samples100restart),
                                    length(mseClaytonLoop7samples100restart),
                                    length(mseClaytonLoop8samples100restart),
                                    length(mseClaytonLoop9samples100restart),
                                    length(mseClaytonLoop10samples100restart),
                                    length(mseClaytonLoop11samples100restart),
                                    length(mseClaytonLoop12samples100restart),
                                    length(mseClaytonLoop13samples100restart),
                                    length(mseClaytonLoop14samples100restart),
                                    length(mseClaytonLoop15samples100restart))

numClaytonLoopSamples1000Restart = c(length(mseClaytonLoop3samples1000restart),
                                     length(mseClaytonLoop4samples1000restart),
                                     length(mseClaytonLoop5samples1000restart),
                                     length(mseClaytonLoop6samples1000restart),
                                     length(mseClaytonLoop7samples1000restart),
                                     length(mseClaytonLoop8samples1000restart),
                                     length(mseClaytonLoop9samples1000restart),
                                     length(mseClaytonLoop10samples1000restart),
                                     length(mseClaytonLoop11samples1000restart),
                                     length(mseClaytonLoop12samples1000restart),
                                     length(mseClaytonLoop13samples1000restart),
                                     length(mseClaytonLoop14samples1000restart),
                                     length(mseClaytonLoop15samples1000restart))

numClaytonLoopSamples10000Restart = c(length(mseClaytonLoop3samples10000restart),
                                      length(mseClaytonLoop4samples10000restart),
                                      length(mseClaytonLoop5samples10000restart),
                                      length(mseClaytonLoop6samples10000restart),
                                      length(mseClaytonLoop7samples10000restart),
                                      length(mseClaytonLoop8samples10000restart),
                                      length(mseClaytonLoop9samples10000restart),
                                      length(mseClaytonLoop10samples10000restart),
                                      length(mseClaytonLoop11samples10000restart),
                                      length(mseClaytonLoop12samples10000restart),
                                      length(mseClaytonLoop13samples10000restart),
                                      length(mseClaytonLoop14samples10000restart),
                                      length(mseClaytonLoop15samples10000restart))

numNormalLoopSamples100Barrier = c(length(mseNormalLoop3samples100barrier),
                                   length(mseNormalLoop4samples100barrier),
                                   length(mseNormalLoop5samples100barrier),
                                   length(mseNormalLoop6samples100barrier),
                                   length(mseNormalLoop7samples100barrier),
                                   length(mseNormalLoop8samples100barrier),
                                   length(mseNormalLoop9samples100barrier),
                                   length(mseNormalLoop10samples100barrier),
                                   length(mseNormalLoop11samples100barrier),
                                   length(mseNormalLoop12samples100barrier),
                                   length(mseNormalLoop13samples100barrier),
                                   length(mseNormalLoop14samples100barrier),
                                   length(mseNormalLoop15samples100barrier))

numNormalLoopSamples1000Barrier = c(length(mseNormalLoop3samples1000barrier),
                                    length(mseNormalLoop4samples1000barrier),
                                    length(mseNormalLoop5samples1000barrier),
                                    length(mseNormalLoop6samples1000barrier),
                                    length(mseNormalLoop7samples1000barrier),
                                    length(mseNormalLoop8samples1000barrier),
                                    length(mseNormalLoop9samples1000barrier),
                                    length(mseNormalLoop10samples1000barrier),
                                    length(mseNormalLoop11samples1000barrier),
                                    length(mseNormalLoop12samples1000barrier),
                                    length(mseNormalLoop13samples1000barrier),
                                    length(mseNormalLoop14samples1000barrier),
                                    length(mseNormalLoop15samples1000barrier))

numNormalLoopSamples10000Barrier = c(length(mseNormalLoop3samples10000barrier),
                                     length(mseNormalLoop4samples10000barrier),
                                     length(mseNormalLoop5samples10000barrier),
                                     length(mseNormalLoop6samples10000barrier),
                                     length(mseNormalLoop7samples10000barrier),
                                     length(mseNormalLoop8samples10000barrier),
                                     length(mseNormalLoop9samples10000barrier),
                                     length(mseNormalLoop10samples10000barrier),
                                     length(mseNormalLoop11samples10000barrier),
                                     length(mseNormalLoop12samples10000barrier),
                                     length(mseNormalLoop13samples10000barrier),
                                     length(mseNormalLoop14samples10000barrier),
                                     length(mseNormalLoop15samples10000barrier))

numClaytonLoopSamples100Barrier = c(length(mseClaytonLoop3samples100barrier),
                                    length(mseClaytonLoop4samples100barrier),
                                    length(mseClaytonLoop5samples100barrier),
                                    length(mseClaytonLoop6samples100barrier),
                                    length(mseClaytonLoop7samples100barrier),
                                    length(mseClaytonLoop8samples100barrier),
                                    length(mseClaytonLoop9samples100barrier),
                                    length(mseClaytonLoop10samples100barrier),
                                    length(mseClaytonLoop11samples100barrier),
                                    length(mseClaytonLoop12samples100barrier),
                                    length(mseClaytonLoop13samples100barrier),
                                    length(mseClaytonLoop14samples100barrier),
                                    length(mseClaytonLoop15samples100barrier))

numClaytonLoopSamples1000Barrier = c(length(mseClaytonLoop3samples1000barrier),
                                     length(mseClaytonLoop4samples1000barrier),
                                     length(mseClaytonLoop5samples1000barrier),
                                     length(mseClaytonLoop6samples1000barrier),
                                     length(mseClaytonLoop7samples1000barrier),
                                     length(mseClaytonLoop8samples1000barrier),
                                     length(mseClaytonLoop9samples1000barrier),
                                     length(mseClaytonLoop10samples1000barrier),
                                     length(mseClaytonLoop11samples1000barrier),
                                     length(mseClaytonLoop12samples1000barrier),
                                     length(mseClaytonLoop13samples1000barrier),
                                     length(mseClaytonLoop14samples1000barrier),
                                     length(mseClaytonLoop15samples1000barrier))

numClaytonLoopSamples10000Barrier = c(length(mseClaytonLoop3samples10000barrier),
                                      length(mseClaytonLoop4samples10000barrier),
                                      length(mseClaytonLoop5samples10000barrier),
                                      length(mseClaytonLoop6samples10000barrier),
                                      length(mseClaytonLoop7samples10000barrier),
                                      length(mseClaytonLoop8samples10000barrier),
                                      length(mseClaytonLoop9samples10000barrier),
                                      length(mseClaytonLoop10samples10000barrier),
                                      length(mseClaytonLoop11samples10000barrier),
                                      length(mseClaytonLoop12samples10000barrier),
                                      length(mseClaytonLoop13samples10000barrier),
                                      length(mseClaytonLoop14samples10000barrier),
                                      length(mseClaytonLoop15samples10000barrier))

plot(3:15, mediansNormalLoopSamples1000GradDescent, pch = 4)
lines(3:15, mediansNormalLoopSamples1000GradDescent + sdMediansNormalLoopSamples1000GradDescent * abs(qt(0.05/2, 10) / sqrt(numNormalLoopSamples1000GradDescent)))